server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: rocketyou1@mysql
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to daily code buffer from dev!!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"



#
#---
#
#spring:
#  profiles: qa
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    password: rocketyou1@mysql
#    url: jdbc:mysql://localhost:3306/dcbapp-qa
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: Welcome to daily code buffer from qa!!!
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    password: rocketyou1@mysql
#    url: jdbc:mysql://localhost:3306/dcbapp-prod
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: Welcome to daily code buffer from prod!!!